# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d0045571748bef7d47d1af82f1e7163"
name = "Discount Study Live Version"
handle = "discount-study-live-version"
application_url = "https://47.76.174.219"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "najian-develop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://47.76.174.219/auth/callback",
  "https://47.76.174.219/auth/shopify/callback",
  "https://47.76.174.219/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
