# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ab89ef0ce1a4c6d6dd003abd5e21495"
application_url = "https://pix-precipitation-bk-belle.trycloudflare.com"
embedded = true
name = "Discount Study Dev Version"
handle = "discount-study-dev-version"

[build]
include_config_on_deploy = true
dev_store_url = "najian-develop.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://pix-precipitation-bk-belle.trycloudflare.com/auth/callback",
  "https://pix-precipitation-bk-belle.trycloudflare.com/auth/shopify/callback",
  "https://pix-precipitation-bk-belle.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
