# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d0045571748bef7d47d1af82f1e7163"
name = "Discount Study Rust Version"
handle = "build-a-discount-function"
application_url = "https://costa-tariff-quarter-mega.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3a22a586.myshopify.com"
include_config_on_deploy = true

# [START discount-allocator.access_scopes]
[access_scopes]
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products"
# [END discount-allocator.access_scopes]

[auth]
redirect_urls = [
  "https://costa-tariff-quarter-mega.trycloudflare.com/auth/callback",
  "https://costa-tariff-quarter-mega.trycloudflare.com/auth/shopify/callback",
  "https://costa-tariff-quarter-mega.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
